spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kassadin?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  data:
    mongodb:
      host: localhost
      port: 27017
      database: kassadin-port
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /kassadin
    username: kassadin
    password: kassadin
# 日志配置
logging:
  level:
    root: info
    com.yosamaru.kassadin: debug
logstash:
  host: localhost