spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kassadin?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
logging:
  level:
    root: info
    com.yosamaru.kassadin: debug
logstash:
  host: localhost